### ISSUE TITLE
Color prop is not working

### ISSUE THREAD

**Issue by zhil** [klendi/react-top-loading-bar#12]
First of all, thanks for great module!

I am trying to change color using code like 
```
<LoadingBar
   height={10}
   color='#ff9b20'
   onRef={ref => (this.LoadingBar = ref)}
   />
```
but its still red. In final html code I dont have background-color property in styles, only height  

![image](https://user-images.githubusercontent.com/981783/64071918-e111b580-cc8d-11e9-9cc6-422842074172.png)

After playing around with sources I founded a bug - looks like you cant use backgroundColor with bacground in style property (even if background is empty)

code like
```
                <h1>Not working color</h1>
                <div style={{height:"10px"}}>
                    <div style={{backgroundColor: "#ff9b20", background: "", width: "40%", height: "10px"}}></div>
                </div>
                <h1>Working</h1>
                <div style={{height:"10px"}}>
                    <div style={{backgroundColor: "#ff9b20", width: "40%", height: "10px"}}></div>
                </div>
```
would produce output
![image](https://user-images.githubusercontent.com/981783/64072161-a3fbf200-cc92-11e9-8f02-b929a5f13a95.png)

I am not sure about your usecases for background prop, so I cant make PR

I have added simple repo, so you can check this bug yourself
https://github.com/zhil/preloader-bug

Function barStyle() need to be fixed
https://github.com/klendi/react-top-loading-bar/blob/master/src/index.tsx#L222

**Comment by zhil** [comment]
@klendi will you be able to fix this issue?

**Comment by klendi** [comment]
Hello. Try removing color prop and use `background` prop.

**Comment by klendi** [comment]
Also are you using the latest example. Tell me your version. Seems to work fine for my example that is on github

![image](https://user-images.githubusercontent.com/20234738/64080196-bce7c000-ccf1-11e9-9a81-57ebf844a2ad.png)
This is the code of the example and its using latest version and color prop.

**Comment by klendi** [comment]
Solved at last commit. :)
