### ISSUE TITLE
Pass height to inner div

### ISSUE THREAD

**Issue by lu-zen** [klendi/react-top-loading-bar#14]
Hi!

`<div style={{ height }}>
        {show ? (
          <div
            className={
              styles['loading-bar'] +
              ' ' +
              (className || '') +
              ' ' +
              (full ? styles['loading-bar-full'] : '')
            }
            style={this.barStyle()}
          />
        ) : null}
      </div>`

The progress bar is rendered as 2 nested divs, the external div only serves the pupose of setting bar height. The first div is static and leaves an empty space on the top of the viewport.
Why not drop the external div and pass the height prop ?

**Comment by klendi** [comment]
Hello. Yeah you're right. Now I am thinking of a new feature. What if we have a property to set the color of the external div. It can be used like health bars etc. Will work on it, will consider this feature or perhaps remove it. :)

**Comment by lu-zen** [comment]
Nice, tell me if you need any help. The workaround atm is select the div and apply `position: fixed`.

**Comment by rhythmpatel** [comment]
I too had the same issue. I added a wrapper `div` and added fixed position.
```
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  height: 4px;
  z-index: 9999;
```

**Comment by klendi** [comment]
This got implemented on the latest version! v2
