### ISSUE TITLE
Issue with `continuousStart` and async `complete`

### ISSUE THREAD

**Issue by pierre-borckmans** [klendi/react-top-loading-bar#15]
Hi there, thanks for this nice component!

I'm running into a small issue or I might be overlooking something.

Here is an example of the problem:
[https://codesandbox.io/s/long-wind-ud61h](https://codesandbox.io/s/long-wind-ud61h)

If you click the `Fake fetch` button, you will see that after the `complete` method is called asynchronously, the continuous progress continues.

The fake fetch method basically does this:
```
    this.LoadingBar.continuousStart(0);
    setTimeout(() => this.complete(), 2000);
```

Am I missing something?

**Comment by pierre-borckmans** [comment]
I went ahead and created a PR that might be a quick solution for this: #16

**Comment by klendi** [comment]
Well this is hella out of a weird bug 😄.

**Comment by klendi** [comment]
Check my response at #16
