### ISSUE TITLE
CSP - CSS Injector

### ISSUE THREAD

**Issue by AndrePinto-NET** [klendi/react-top-loading-bar#18]
The CSS injector violates a secure content security policy. In order for this to work, unsafe-inline must be used on the style-src attribute.

It should be possible to define if we want to import the CSS manually or automatically. In my opinion, you could completely remove the automatic inject of CSS, because this is insecure.

**Comment by klendi** [comment]
@AndrePinto-NET hello.

**Comment by klendi** [comment]
@AndrePinto-NET hello. yes that might be insecure but that was the way to go the library boilerplate generator I used. What should I replace it with ? styled-components. That will just make the size huge. also can't make it inline since it has animations in the css lines. What do you suggest?

**Comment by klendi** [comment]
A new typescript version is coming that is going to fix this.

**Comment by klendi** [comment]
Css injection is removed from the latest version.
