### ISSUE TITLE
Loading bar throws an exception on unmount if not using refs

### ISSUE THREAD

**Issue by codinronan** [klendi/react-top-loading-bar#2]
Hi there,

There's an issue introduced in your latest changes:

https://github.com/klendi/react-top-loading-bar/blame/bc6077646e3a38d70f6d3e7e0ce0310f719f9f8f/src/index.js#L115

If the consumer does not use the `ref` property, this line of code throws an exception on unmount, crashing the page.

**Comment by klendi** [comment]
Thank you for this bug report. Fixed it and published fresh package to npm.
Feel free to reopen if you encounter any other issues.
