### ISSUE TITLE
Use <LoadingBar> on React Functional Component

### ISSUE THREAD

**Issue by Heni-ghodbane** [klendi/react-top-loading-bar#20]
Is it possible to use LoadingBar on React Functional Component?

**Comment by klendi** [comment]
Yes ofc. You can just create a functional component and use it. You can use either the refs or you can use `useState` hook to copntrol the loading bar amount and movement. Just like in a class component.
Closing this. Feel free to reopen if you have any more issues.

**Comment by Heni-ghodbane** [comment]
Of course, I've used the useState hook for the properties, (color, progress ..)  
but the Tag `<LoadingBar>` does not work (in another way, it will not be rendered as HTML element)
This is the error message: `ReferenceError: LoadingBar is not defined`

**Comment by klendi** [comment]
Can you show the exact code how you using it ?

**Comment by Heni-ghodbane** [comment]
Just  like this:

> import React, { useState, useEffect, useRef } from 'react';
> import LoadingBar from 'react-top-loading-bar';

> const HomePage = props => {
> 
> const [colorBar, setColorBar] = useState('#28b485');
> 
> let content = (
>     <LoadingBar height={3} color={colorBar} onRef={(ref) => (LoadingBar = ref)} />
> );
> 	return content;
> }
> export default HomePage; 

I guess something is missed in your Library, because I am using some other libs with the same way.

**Comment by klendi** [comment]
Oh I see the problem. You are actually trying to assign a variable at `onRef={(ref) => (LoadingBar = ref)}`. but variable `LoadingBar` is undefined. In class component case we use `this.LoadingBar`

You can try something like this
```let loadingBar = null``` 
and when using the component tag use
 ```<LoadingBar height={3} color={colorBar} onRef={(ref) => (loadingBar = ref)} />```

Then you can access the `loadingBar` variable.

**Comment by Heni-ghodbane** [comment]
This still not solving the problem, error on this line 

> LoadingBar.staticStart();

`Uncaught TypeError: react_top_loading_bar__WEBPACK_IMPORTED_MODULE_4__.default.staticStart is not a function`

**Comment by klendi** [comment]
Yeah sorry. I will take a look at it. Meanwhile you can try using the progress prop. You can manually emulate the loading bar behavior.

**Comment by klendi** [comment]
it should work if you create a react ref and assign it on ref={reactRef}. Then access the methods.

**Comment by n0ne** [comment]
Sorry, it doesn't work for me. I mean ref={reactRef}

**Comment by klendi** [comment]
create react ref using hooks. `const ref = useRef(null)` and `ref={ref}`. Try this @n0ne

**Comment by n0ne** [comment]
@klendi I did, but: Uncaught TypeError: ref.continuousStart is not a function

**Comment by n0ne** [comment]
@klendi I have to use `ref.current.continuousStart`

**Comment by stephen-last** [comment]
@klendi & @n0ne  I can't get this working, I don't understand where `ref={ref}` goes. We could do with a full functional component example. I have:

```js
function SitesList (props) {
  const [loadingBarProgress, updateProgress] = useState(0)
  const loadingBar = useRef(null)

  const loading = <LoadingBar
    progress={loadingBarProgress}
    height={3}
    color='red'
    onLoaderFinished={() => updateProgress(0)}
    onRef={(ref) => {
      loadingBar.current = ref
    }}
  />

  loadingBar.current.continuousStart()

  return (...)
}
```

Error = `loadingBar.current is null`

How do we access `LoadingBar` methods in a functional component..?
