### ISSUE TITLE
onLoadFinshed not taking effect

### ISSUE THREAD

**Issue by Joshmatjjen** [klendi/react-top-loading-bar#32]
`
const [loadBar, setLoadBar] = useState();`
`const onLoaderFinished = num => {`
      `setLoadBar(num);`
    `};`
`return(`
`<LoadingBar`
          `progress={loadBar}`
         ` height={3}`
        `  color={barColor}`
          `onLoaderFinished={() => onLoaderFinished(20)}`
       ` />`
`)`

**Comment by klendi** [comment]
This got fixed on v2. Check the new version in here https://klendi.github.io/react-top-loading-bar/
