### ISSUE TITLE
Make it work with HTTP Calls

### ISSUE THREAD

**Issue by hasante** [klendi/react-top-loading-bar#34]
You got me, but please add this feature it will go a long way

**Comment by klendi** [comment]
what do you mean http calls ? You can "simulate" http calls, like start the bar on request beginning, and end it on result. You can even use redux

**Comment by hasante** [comment]
I have seen a react package like this that works with Redux to make HTTP calls possible.

I was thinking maybe you could do this for only react.js without the need to integrating Redux.
What are your taughts?

**Comment by klendi** [comment]
Yeah but there are can multiple http calls, or 3 calls async, loading bar would go crazy, I don't think it's a good idea. It's more controllable or appropriate to only activate the bar when needed. It gives more control. And more popular bars don't have that. Bars are meant to have start -> end, the loading is just a simulation, we can't track http calls progress that much. Also you have project examples where I used the bar on my other projects.

**Comment by hasante** [comment]
Well, I am talking of user-initiated calls, but until you have tried looking into it and prioritizing a part of the scenario. I am not sure you can straightaway assume that has to be all you state up here.

This can serve as a start: https://github.com/aitboudad/ngx-loading-bar/blob/master/packages/http-client/README.md

React Redux version: https://github.com/mironov/react-redux-loading-bar

The importance from my perspective is there is a load of redundancy involved in importing your package everywhere you want to use it.

The problem here is that they integrate into the HTTP module of angular to make this possible. For my idea, I was thinking you can find a way around it. Say something creative as any calls after a component is loaded or something else.

I am sure there is a way, think about it, If it's not possible then you would have tried.

**Comment by ndodanli** [comment]
> Well, I am talking of user-initiated calls, but until you have tried looking into it and prioritizing a part of the scenario. I am not sure you can straightaway assume that has to be all you state up here.
> 
> This can serve as a start: https://github.com/aitboudad/ngx-loading-bar/blob/master/packages/http-client/README.md
> 
> React Redux version: https://github.com/mironov/react-redux-loading-bar
> 
> The importance from my perspective is there is a load of redundancy involved in importing your package everywhere you want to use it.
> 
> The problem here is that they integrate into the HTTP module of angular to make this possible. For my idea, I was thinking you can find a way around it. Say something creative as any calls after a component is loaded or something else.
> 
> I am sure there is a way, think about it, If it's not possible then you would have tried.

I organized the code for HTTP calls and used with redux/without redux.  I also tried https://github.com/mironov/react-redux-loading-bar and this didn't work for me and had bugs. If you still have trouble with it you can contantc me ndodanli14@gmail.com

**Comment by khooz** [comment]
This is a specialization of a generic component IMHO. Since there are many 3rd party libraries for remote calls along the fairly new `fetch`, and in my case, I tend to use those 3rd party libraries still even when there's a native API in the standard, because, not all browsers still support it and using a polyfill is just the same as using a 3rd party lib without the extra oomph.

I think this is rather pointless in this state of browser market share, or at least as long as there are non deprecated browsers and browser versions that does not yet support native `fetch` API; especially in the enterprise environments.
