### ISSUE TITLE
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended.

### ISSUE THREAD

**Issue by sndrjhlncgr** [klendi/react-top-loading-bar#35]
* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

i get this type of warning.

**Comment by klendi** [comment]
This got fixed on v2.
