### ISSUE TITLE
Support style prop

### ISSUE THREAD

**Issue by kevinswarner** [klendi/react-top-loading-bar#40]
Thanks for this component! I know that you can provide a className and use a stylesheet to style the component, but it would also be nice to just be able to use a style prop. I use CSS-in-JS and don't often add full style sheets. Something like this...

```javascript
<LoadingBar ref={ref} style={{ width: '50%' }} />
```

Just a suggestion. Thank you!

**Comment by klendi** [comment]
That is actually a good idea. Will find time and add it. Thank you!

**Comment by klendi** [comment]
Sorry for the late late change but I added `style` which is for loader, and `containerStyle` which is for container. Maybe someone will need this in the future. Thank you
