### ISSUE TITLE
Call hook outside react context

### ISSUE THREAD

**Issue by fijemax** [klendi/react-top-loading-bar#44]
Hello,

I used react-top-loading-bar in a simple way in a component library:
```
      <LoadingBar
        shadow={false}
        progress={missionsDownloadProgress}
        height={3}
        color='#00AAC2'
      />
```
So when I link the library to my application, I have a hook problem:
![image](https://user-images.githubusercontent.com/16467651/111287796-dcc8a580-8643-11eb-8193-90329ac7fb49.png)

I inspected hook in react-top-loading-bar code and didn't find anything ... but in the file index.modern.js from npmjs package I found this:
![image](https://user-images.githubusercontent.com/16467651/111288065-21ecd780-8644-11eb-8264-675837125df4.png)
and it seems corrrspond to this code:
![image](https://user-images.githubusercontent.com/16467651/111288203-421c9680-8644-11eb-8866-78a23cd21703.png)

To summaries:
```Object(__WEBPACK_IMPORTED_MODULE_0_react__["useRef"])```   => ```checkIfFull```

I deleted the ```index.modern.js" frile from the node_module package ```react-top-loading-bar``` and webpack used ```index.js``` file instead, and seems work perfectly. But I don't know how to configure webpack to use ```index.js``` instead of ```index.modern.js``` and I don't know if ```index.modern.js``` is generated correctly.

**Comment by klendi** [comment]
Interesting, this never occurred to me before. 
Why don't you use onLoaderFinished(), to reset the progress. `      <LoadingBar color="#f11946" progress={progress} onLoaderFinished={() => setProgress(0)} />
`
Can you share more details on how can I reproduce this, react version, are you using next / cra / gatsby, etc. Also is it just a warning or does it crash ?

**Comment by fijemax** [comment]
I tryed with the onLoader FInished callback prop but I got the same problem.
What i find weird that is seem normal that index.modern.js crash by seeing the code, no ?
It's a crash, but it seem appear in a timeout callback (which would seem logical given the hook react context error), but we have many sentry about it.

**Comment by fijemax** [comment]
we are using "react": "^16.8.2"

**Comment by khooz** [comment]
@fijemax Is this still an issue? Can you please provide a self contained reproducible example?
