### ISSUE TITLE
className does not work!

### ISSUE THREAD

**Issue by andriuszibaitis** [klendi/react-top-loading-bar#45]
When I add:
<LoadingBar
        className="loading"
        progress={progress}
        onLoaderFinished={() => setProgress(0)}
      />

Styles:
  .loading {
    background: #FFF; 
  }

The color remains red.
It's not working. How to change loading bar color with className?

**Comment by klendi** [comment]
The className works but since it is using inline styles for props that's maybe it's not working, try adding !important

**Comment by klendi** [comment]
I added two classNames props, one for container `containerClassName`  and for the loader itself, "className"
