### ISSUE TITLE
Using in-built functions with React Hooks ref doesn't work

### ISSUE THREAD

**Issue by sreetamdas** [klendi/react-top-loading-bar#5]
I am using [React Hooks](https://reactjs.org/docs/hooks-intro.html) for a personal project, and wanted to use the in-built `LoadingBar.continousStart()` function. I understand how this would work if my Loader component was a stateful component, your example is pretty clear on that:
```
<LoadingBar
...
onRef={ref => {this.loadingBarRef = ref}}
/>
```

But in my scenario, I am using hooks, which pretty much eliminates the `this` keyword. There is a [Hooks API for `refs`](https://reactjs.org/docs/hooks-reference.html#useref) that I have utilized for my other functional components, but when I do the same thing for `LoadingBar`, I get the following error:

>  Warning: Failed prop type: Invalid prop `onRef` of type `object` supplied to `LoadingBar`, expected `function`.

Is there a solution for this? 
Thanks for the library btw, it's really nice 😄

**Comment by klendi** [comment]
Hello @sreetamdas. Sorry for the late reply but I have been a bit busy. Also did you find a fix for this? Haven't tried hooks `useRef` just yet. So I don't know how it works just yet. If you find a find you can post it here or make a PR. Meanwhile im on it. Cheers and I'm glad you like the library :).

**Comment by sreetamdas** [comment]
Hi @klendi, sorry but I resorted to using another lib; but I think I'll probably fork your repo later and work on making it hooks-compatible myself // rewrite it in hooks. Cheers! 😄

**Comment by sreetamdas** [comment]
@klendi I'm new to rollup and not able to figure out how to run your repo locally, could you provide any resources that halp me set it up on my `localhost`?
