### ISSUE TITLE
is it possible to use a gradient on the loading bar? 

### ISSUE THREAD

**Issue by davidawad** [klendi/react-top-loading-bar#6]
Hey there, great component! Thanks for the contribution! I'm wondering if it's possible to get gradients or background images on it? 

Something like this? 

```
      <LoadingBar
          progress={ someProgressFunc }
          height={3}
          // color="red"
          backgroundImage="linear-gradient(90deg, rgba(2,0,36,1) 0%, #00AD00 50%, #0077AD 100%)"
          onLoaderFinished={() => this.onLoaderFinished()}
        />

```

thanks

**Comment by klendi** [comment]
Yes it is possible I guess. But I need to implement it. That cannot be passed to the component just yet. But it can be done, I will work on it, or you can make a PR if you wish.

**Comment by davidawad** [comment]
awesome! I don't have too much extra time but i'll keep my eyes out for an update! Feel free to let me know over email (me@davidawad.com) if it gets added! 

Thanks @klendi !

**Comment by klendi** [comment]
I just added it at this commit bdc2dde06460537bd318cfbfbe392a9407bd713d and the package just got published to npm. Now you can use the `background` property of the bar, its exactly the css `background` property of the bar. Thank you
