### ISSUE TITLE
error while installing this package in react.

### ISSUE THREAD

**Issue by nilaylabha** [klendi/react-top-loading-bar#63]
### LOG FIle
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'i',
0 verbose cli   'react-top-loading-bar'
0 verbose cli ]
1 info using npm@8.5.5
2 info using node@v16.15.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 10ms
6 timing config:load:builtin Completed in 10ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\admin\Desktop\mywork\newsapp\.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:C:\Users\admin\.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\admin\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 24ms
19 timing npm:load:configload Completed in 24ms
20 timing npm:load:setTitle Completed in 0ms
21 timing config:load:flatten Completed in 4ms
22 timing npm:load:display Completed in 6ms
23 verbose logfile C:\Users\admin\AppData\Local\npm-cache\_logs\2022-05-20T06_48_25_449Z-debug-0.log
24 timing npm:load:logFile Completed in 64ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 97ms
28 timing arborist:ctor Completed in 2ms
29 silly logfile start cleaning logs, removing 3 files
30 timing idealTree:init Completed in 1778ms
31 timing idealTree:userRequests Completed in 9ms
32 silly idealTree buildDeps
33 silly fetch manifest react-top-loading-bar@*
34 silly logfile error removing log file C:/Users/admin/AppData/Local/npm-cache/_logs/2022-05-20T05_03_57_603Z-debug-0.log [Error: EPERM: operation not permitted, lstat 'C:\Users\admin\AppData\Local\npm-cache\_logs\2022-05-20T05_03_57_603Z-debug-0.log'] {
34 silly logfile   errno: -4048,
34 silly logfile   code: 'EPERM',
34 silly logfile   syscall: 'lstat',
34 silly logfile   path: 'C:\\Users\\admin\\AppData\\Local\\npm-cache\\_logs\\2022-05-20T05_03_57_603Z-debug-0.log'
34 silly logfile }
35 timing arborist:ctor Completed in 0ms
36 http fetch GET 200 https://registry.npmjs.org/react-top-loading-bar 1278ms (cache hit)
37 silly fetch manifest react@^18.1.0
38 http fetch GET 200 https://registry.npmjs.org/react 16ms (cache hit)
39 silly fetch manifest react@^16 || ^17
40 timing idealTree Completed in 3121ms
41 timing command:i Completed in 3143ms
42 verbose stack Error: unable to resolve dependency tree
42 verbose stack     at Arborist.[failPeerConflict] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1398:25)
42 verbose stack     at Arborist.[loadPeerSet] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1364:34)
42 verbose stack     at async Arborist.[buildDepStep] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:950:11)
42 verbose stack     at async Arborist.buildIdealTree (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:216:7)
42 verbose stack     at async Promise.all (index 1)
42 verbose stack     at async Arborist.reify (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:153:5)
42 verbose stack     at async Install.exec (C:\Program Files\nodejs\node_modules\npm\lib\commands\install.js:159:5)
42 verbose stack     at async module.exports (C:\Program Files\nodejs\node_modules\npm\lib\cli.js:66:5)
43 verbose cwd C:\Users\admin\Desktop\mywork\newsapp
44 verbose Windows_NT 10.0.19044
45 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "react-top-loading-bar"
46 verbose node v16.15.0
47 verbose npm  v8.5.5
48 error code ERESOLVE
49 error ERESOLVE unable to resolve dependency tree
50 error
51 error While resolving: [1mnewsapp[22m@[1m0.1.0[22m
51 error Found: [1mreact[22m@[1m18.1.0[22m[2m[22m
51 error [2mnode_modules/react[22m
51 error   [1mreact[22m@"[1m^18.1.0[22m" from the root project
51 error
51 error Could not resolve dependency:
51 error [35mpeer[39m [1mreact[22m@"[1m^16 || ^17[22m" from [1mreact-top-loading-bar[22m@[1m2.1.0[22m[2m[22m
51 error [2mnode_modules/react-top-loading-bar[22m
51 error   [1mreact-top-loading-bar[22m@"[1m*[22m" from the root project
51 error
51 error Fix the upstream dependency conflict, or retry
51 error this command with --force, or --legacy-peer-deps
51 error to accept an incorrect (and potentially broken) dependency resolution.
51 error
51 error See C:\Users\admin\AppData\Local\npm-cache\eresolve-report.txt for a full report.
52 verbose exit 1
53 timing npm Completed in 3808ms
54 verbose unfinished npm timer reify 1653029306091
55 verbose unfinished npm timer reify:loadTrees 1653029306106
56 verbose unfinished npm timer idealTree:buildDeps 1653029307896
57 verbose unfinished npm timer idealTree:#root 1653029307897
58 verbose code 1
59 error A complete log of this run can be found in:
59 error     C:\Users\admin\AppData\Local\npm-cache\_logs\2022-05-20T06_48_25_449Z-debug-0.log

### error showing
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: newsapp@0.1.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16 || ^17" from react-top-loading-bar@2.1.0
npm ERR! node_modules/react-top-loading-bar
npm ERR!   react-top-loading-bar@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\admin\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Local\npm-cache\_logs\2022-05-20T06_48_25_449Z-debug-0.log

**Comment by dearlordylord** [comment]
Could you try this fork https://github.com/klendi/react-top-loading-bar/pull/64
