### ISSUE TITLE
Typo on function name

### ISSUE THREAD

**Issue by rdsedmundo** [klendi/react-top-loading-bar#9]
continousStart should be continuousStart. :)

Since this is a breaking change, maybe you could add the correct one and add a deprecation notice on the one with the incorrect name.

**Comment by klendi** [comment]
Yep I noticed that after I pushed the code lol, it was my typo. Was too afraid to change since it was a breaking change. Will do soon. Thank you

**Comment by klendi** [comment]
Done on latest commit.
